spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/league_manager
    username: YOUR_DB_USER
    password: YOUR_DB_PASSWORD

jwt:
  secret: YOUR_SECRET

resend:
  api:
    key: YOUR_RESEND_API_KEY

server:
  port: 8080
